### ISSUE TITLE
404 links

### ISSUE THREAD

**Issue by tiborsaas** [WhitestormJS/whitestormjs.github.io#4]
Hello,

Links on the docs page are 404:
http://whitestormjs.xyz/FirstPerson

All links from controls to posteffects.

**Comment by laszlolm** [comment]
@tiborsaas it's 404 because it is not working per sec

**Comment by sasha240100** [comment]
@tiborsaas We hadn't written all docs yet because it is still dev version. I think that this one is last, so we will publish beta in a week:) and will write all docs!

Main reason is that API is always changing. But now we are closer to final version.

P.s.: We are going to move Wagner effects, and use it as a plugin.

**Comment by tiborsaas** [comment]
Thx @sasha240100 I encourage you, because it looks broken at the most crucial part of the project. I stopped reading the page at 404 and didn't read it's not completed yet. Maybe just remove the 404 code or provide empty coming soon pages. Looking forward to play with it.

**Comment by ghost** [comment]
Lol
